name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1000
          repository: ${{secrets.USERNAME}}/${{secrets.BACKEND_REPO}}
          path: backend
      - name: Testing Backend
        run: |
          cd backend
          npm install
          npm test
      - uses: actions/checkout@v2
        with:
          repository: ${{secrets.USERNAME}}/${{secrets.FRONTEND_REPO}}
          path: frontend
      - name: Testing frontend
        run: |
          cd frontend
          npm install
          npm test
      - name: Building frontend
        run: |
          cd frontend
          npm run build
          mv build ../backend/
          cd ..
          rm -rf frontend
      - uses: actions/checkout@v2
        with:
          repository: ${{secrets.USERNAME}}/${{secrets.BUILD_REPO}}
          path: build
      - name: Push to Build Repo
        run: |
          cd build
          rm -rf ../backend/.git ../backend/.github
          mv ../backend/* .
          rm -rf node_modules
          # git config --global user.email "58025059+shiviraj@users.noreply.github.com"
          # git config --global user.name ${{secrets.USERNAME}}
          # git add .
          # git commit -m "added build"
          # git push -f;
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
